[build-system]
requires = [
    "robotpy-build>=2020.2.0,<2021.0.0",
    "robotpy-wpiutil>=2020.3.2.0,<2021.0.0",
]

[tool.robotpy-build]
base_package = "_pyntcore"

[tool.robotpy-build.wrappers."_pyntcore".maven_lib_download]
artifact_id = "ntcore-cpp"
group_id = "edu.wpi.first.ntcore"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "2020.3.2"

libs = ["ntcore"]

[tool.robotpy-build.wrappers."_pyntcore"]
name = "ntcore"
sources = [
    "_pyntcore/src/ntcore.cpp",
    "_pyntcore/src/nt_logging.cpp",
    "_pyntcore/src/py2value.cpp",
    "_pyntcore/src/pyentry.cpp",
]

depends = ["wpiutil"]

generate = [
    { NetworkTable = "networktables/NetworkTable.h"},
    { NetworkTableEntry = "networktables/NetworkTableEntry.h"},
    { NetworkTableInstance = "networktables/NetworkTableInstance.h"},
    { NetworkTableType = "networktables/NetworkTableType.h"},
    { NetworkTableValue = "networktables/NetworkTableValue.h"},
    { CppApi = "ntcore_cpp.h"},
]

generation_data = "gen"


[tool.robotpy-build.metadata]
name = "pyntcore"
description = "Binary wrappers for the FRC ntcore library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/pyntcore"
license = "BSD-3-Clause"
install_requires = [
    "robotpy-wpiutil>=2020.3.2.0,<2021.0.0",
    "pynetworktables>=2020.0.3,<2021.0.0",
]
